### ISSUE TITLE
Windows11下运行失败

### ISSUE THREAD

**Issue by huangsijun17** [LyzenX/DouyinLiveRecorder#15]
> python --version
> Python 3.11.3

> 版本	Windows 11 专业版
> 版本	22H2
> 安装日期	‎2023/‎5/‎4
> 操作系统版本	22621.1702
> 体验	Windows Feature Experience Pack 1000.22641.1000.0

![image](https://github.com/LyzenX/DouyinLiveRecorder/assets/31504595/64f1cbce-a996-4adc-9b0a-eb0ba2b18efa)

```
PS D:\直播录制程序\DouyinLiveRecorder> pip install -r .\requirements.txt
Requirement already satisfied: requests~=2.28.2 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from -r .\requirements.txt (line 1)) (2.28.2)
Requirement already satisfied: websocket-client~=1.5.1 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from -r .\requirements.txt (line 2)) (1.5.2)
Requirement already satisfied: protobuf==3.6.0 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from -r .\requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: setuptools in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from protobuf==3.6.0->-r .\requirements.txt (line 3)) (65.5.0)
Requirement already satisfied: six>=1.9 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from protobuf==3.6.0->-r .\requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from requests~=2.28.2->-r .\requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from requests~=2.28.2->-r .\requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from requests~=2.28.2->-r .\requirements.txt (line 1)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\videographer\appdata\local\programs\python\python311\lib\site-packages (from requests~=2.28.2->-r .\requirements.txt (line 1)) (2023.5.7)
PS D:\直播录制程序\DouyinLiveRecorder> python .\main.pyw
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\util\logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\util\logger.py", line 65, in fatal_and_print
    if not app.win_mode:
           ^^^^^^^^^^^^
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "D:\直播录制程序\DouyinLiveRecorder\main.pyw", line 3, in <module>
    import dylr.core.app as app
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\core\app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\core\config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\core\record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\core\recording.py", line 8, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "D:\直播录制程序\DouyinLiveRecorder\dylr\core\danmu_recorder.py", line 8, in <module>
    from google.protobuf import json_format
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\json_format.py", line 64, in <module>
    from google.protobuf import symbol_database
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\symbol_database.py", line 62, in <module>
    from google.protobuf import message_factory
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\message_factory.py", line 44, in <module>
    from google.protobuf import reflection
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\internal\python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "C:\Users\videographer\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\internal\containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
PS D:\直播录制程序\DouyinLiveRecorder>
```

**Comment by LyzenX** [comment]
python版本多少？使用python 3.8 或 3.9 试试

**Comment by huangsijun17** [comment]
> python版本多少？使用python 3.8 或 3.9 试试

python --version
Python 3.11.3

我降下去试试看。

**Comment by xlhd19980327** [comment]
实测使用conda安装python版本3.9.13，然后用pip install -r requriment.txt即不会出现报错
