### ISSUE TITLE
录制完成后，自动转码功能失效，但是已经部署了ffmpeg

### ISSUE THREAD

**Issue by imzoet** [LyzenX/DouyinLiveRecorder#3]
Win11

log:

2023-03-12 19:49:56,938 [INFO] software started. version: 20230215. gui: True.
2023-03-12 19:49:57,021 [INFO] platform: Windows-10-10.0.22621-SP0
2023-03-12 19:49:57,021 [INFO] python version: 3.8.13
2023-03-12 19:49:57,021 [INFO] reading configs
2023-03-12 19:49:57,021 [INFO] config debug = true
2023-03-12 19:49:57,021 [INFO] config check_period = 25
2023-03-12 19:49:57,021 [INFO] config check_period_random_offset = 5
2023-03-12 19:49:57,021 [INFO] config important_check_period = 5
2023-03-12 19:49:57,021 [INFO] config important_check_period_random_offset = 3
2023-03-12 19:49:57,021 [INFO] config check_threads = 1
2023-03-12 19:49:57,022 [INFO] config check_wait = 0.5
2023-03-12 19:49:57,022 [INFO] config monitor_using_api = true
2023-03-12 19:49:57,022 [INFO] >>> dy api: 1
2023-03-12 19:49:57,022 [INFO] config ffmpeg_path = 
2023-03-12 19:49:57,022 [INFO] config auto_transcode = true
2023-03-12 19:49:57,022 [INFO] config auto_transcode_encoder = copy
2023-03-12 19:49:57,022 [INFO] config auto_transcode_bps = 3000k
2023-03-12 19:49:57,022 [INFO] config auto_transcode_delete_origin = false
2023-03-12 19:49:57,023 [INFO] loaded room: 暗杠(678175807036) auto_record=True record_danmu=False important=True
2023-03-12 19:49:57,023 [INFO] loaded room: 帕尔Parat(163309877195) auto_record=True record_danmu=False important=False
2023-03-12 19:49:57,024 [INFO] 获取cookie中...
2023-03-12 19:50:12,764 [INFO] cookie获取完成
2023-03-12 19:50:19,573 [INFO] 检测到 暗杠(678175807036) 开始直播，启动录制。
2023-03-12 19:50:19,574 [DEBUG] find stream url of 暗杠(678175807036): http://pull-flv-l26.douyincdn.com/third/stream-112650400879870438_uhd.flv?expire=6416f6fc&sign=762e176db1baa008be94cd023bdb47b0. Starting downloading...
2023-03-12 20:21:02,247 [INFO] 暗杠(678175807036) 录制结束
2023-03-12 20:21:02,248 [INFO] 已将 download/暗杠/20230312_195019.flv 加入转码队列
2023-03-12 20:21:02,596 [INFO] 检测到 暗杠(678175807036) 开始直播，启动录制。
2023-03-12 20:21:02,596 [DEBUG] find stream url of 暗杠(678175807036): http://pull-flv-l26.douyincdn.com/third/stream-112650400879870438.flv?expire=6416fe2f&sign=1818aa2f4cecd83c5492321ae06ed961. Starting downloading...
2023-03-12 20:21:06,963 [ERROR] 没有找到ffmpeg可执行文件，无法转码。
2023-03-12 21:48:54,658 [INFO] 暗杠(678175807036) 录制结束
2023-03-12 21:48:54,659 [INFO] 已将 download/暗杠/20230312_202102.flv 加入转码队列
2023-03-12 21:49:00,556 [ERROR] 没有找到ffmpeg可执行文件，无法转码。
2023-03-12 21:59:07,208 [DEBUG] Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\anaconda\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\anaconda\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\anaconda\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\anaconda\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\anaconda\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\anaconda\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\anaconda\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\anaconda\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\anaconda\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\anaconda\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\anaconda\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\anaconda\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\anaconda\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\anaconda\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zoet Lab\Downloads\DouyinLiveRecorder-main\dylr\core\monitor.py", line 134, in check_room
    check_room_using_api(room)
  File "C:\Users\Zoet Lab\Downloads\DouyinLiveRecorder-main\dylr\core\monitor.py", line 147, in check_room_using_api
    room_json = dy_api.get_live_state_json(room.room_id)
  File "C:\Users\Zoet Lab\Downloads\DouyinLiveRecorder-main\dylr\core\dy_api.py", line 41, in get_live_state_json
    req = requests.get(api_url, headers=get_request_headers(), proxies=proxies)
  File "C:\anaconda\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\anaconda\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))

2023-03-12 22:04:07,835 [INFO] GUI closed

**Comment by imzoet** [comment]
以及一场直播不知道为什么分成了两段，中间断了一次，又马上重新录制了一个新的文件

**Comment by imzoet** [comment]
以及一场直播不知道为什么分成了两段，中间断了一次，又马上重新录制了一个新的文件

**Comment by imzoet** [comment]
以及一场直播不知道为什么分成了两段，中间断了一次，又马上重新录制了一个新的文件

**Comment by AlphaYu** [comment]
我也遇到了同样的问题，ffmpeg 已经配置了环境变量了，环境变量验证过配置没有问题。

**Comment by AIRDOGE** [comment]
+1
