### ISSUE TITLE
自动转码出错

### ISSUE THREAD

**Issue by AIRDOGE** [LyzenX/DouyinLiveRecorder#35]
# ffmpeg 的地址，填点(.)为软件根目录，例：D:/software/video/，无需加上 ffmpeg.exe
# 软件默认不带 ffmpeg.exe，请自行下载
# 如果配置好了环境变量，即在任何目录下都可以使用 ffmpeg，则可以不填
ffmpeg_path = .

已将 download/甜御米-/20230827_233125.flv 加入转码队列
Exception in thread Thread-12:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "dylr\core\transcode_manager.py", line 31, in transcode
  File "dylr\core\transcode_manager.py", line 62, in ffmpeg_bin_exist
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
PermissionError: [WinError 5] 拒绝访问。

我的.exe就放在了根目录，系统变量也加了，cmd输入ffmpeg也有版本显示，但就是不能自动转码

**Comment by LyzenX** [comment]
自动转码会对视频造成不可逆的破坏，而抖音传回的视频数据经常会出问题(但能用b站录播姬修复，经ffmpeg转码后无法修复)，正在考虑移除自动转码。

**Comment by AIRDOGE** [comment]
> 复

好吧，直接录制下来的很多都不能调进度条，或者很卡，b站录播姬又太费时间，ffmpeg倒是很快，不过现在都手动一个个文件夹转

**Comment by yincheng0807** [comment]
写个脚本遍历下载目录把.flv后缀的文件转换一下下
