### ISSUE TITLE
windows 报这一串

### ISSUE THREAD

**Issue by QiuCB** [LyzenX/DouyinLiveRecorder#5]
Error in sys.excepthook:
Traceback (most recent call last):
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\util\logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\util\logger.py", line 65, in fatal_and_print
    if not app.win_mode:
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "main.pyw", line 3, in <module>
    import dylr.core.app as app
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\recording.py", line 8, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\danmu_recorder.py", line 11, in <module>
    from dylr.core.dy_protocol import PushFrame, Response, ChatMessage
  File "F:\thunder\DouyinLiveRecorder-main\DouyinLiveRecorder-main\dylr\core\dy_protocol.py", line 35, in <module>
    type=None),
  File "D:\Python\lib\site-packages\google\protobuf\descriptor.py", line 717, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by ruitaiyihao** [comment]
环境不对，执行一下环境那个bat文件就可以了
