### ISSUE TITLE
报错无法运行，已经重新安装过依赖了

### ISSUE THREAD

**Issue by xiaocainiao2020** [LyzenX/DouyinLiveRecorder#50]
之前的版本都是能正常使用的，用了修复弹幕这个最新版的，提示

```
python3 dy_rec.pyw
[root@localhost dy_rec]# python3 dy_rec.pyw
Please install at least one of the following Javascript interpreter.
python packages: quickjs, PyChakra, PyMiniRacer
applications: Gjs, CJS, QuickJS, JavaScriptCore, Node.js.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/www/wwwroot/dy_rec/dylr/util/logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "/www/wwwroot/dy_rec/dylr/util/logger.py", line 65, in fatal_and_print
    if not app.win_mode:
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "dy_rec.pyw", line 4, in <module>
    import dylr.core.app as app
  File "/www/wwwroot/dy_rec/dylr/core/app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "/www/wwwroot/dy_rec/dylr/core/config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "/www/wwwroot/dy_rec/dylr/core/record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "/www/wwwroot/dy_rec/dylr/core/recording.py", line 9, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "/www/wwwroot/dy_rec/dylr/core/danmu_recorder.py", line 12, in <module>
    from dylr.core.dy_pb2 import PushFrame, Response, ChatMessage
ModuleNotFoundError: No module named 'dylr.core.dy_pb2'
```
该怎么办呢？

**Comment by LyzenX** [comment]
方法1：使用python3.8或3.9版本
方法2：参考这个：https://github.com/LyzenX/DouyinLiveRecorder/issues/16

**Comment by xiaocainiao2020** [comment]
> 方法1：使用python3.8或3.9版本 方法2：参考这个：#16

现在好了，本来也还是启动不了，看到最新的提交，改了文件名之后可以正常启动了。dylr/core/dy_pb2.py
