### ISSUE TITLE
error when executed on ubuntu18, cmd

### ISSUE THREAD

**Issue by supersaiyan2019** [LyzenX/DouyinLiveRecorder#6]
python3 main.pyw
-------------------------------------------------

Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/DouyinLiveRecorder/dylr/util/logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "/root/DouyinLiveRecorder/dylr/util/logger.py", line 65, in fatal_and_print
    if not app.win_mode:
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "/root/DouyinLiveRecorder/main.pyw", line 3, in <module>
    import dylr.core.app as app
  File "/root/DouyinLiveRecorder/dylr/core/app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "/root/DouyinLiveRecorder/dylr/core/config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "/root/DouyinLiveRecorder/dylr/core/record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "/root/DouyinLiveRecorder/dylr/core/recording.py", line 8, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "/root/DouyinLiveRecorder/dylr/core/danmu_recorder.py", line 8, in <module>
    from google.protobuf import json_format
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/json_format.py", line 64, in <module>
    from google.protobuf import symbol_database
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/symbol_database.py", line 62, in <module>
    from google.protobuf import message_factory
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/message_factory.py", line 44, in <module>
    from google.protobuf import reflection
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by LyzenX** [comment]
Try downgrading python to 3.8 or 3.9
