### ISSUE TITLE
老哥救救我

### ISSUE THREAD

**Issue by daqiang789** [LyzenX/DouyinLiveRecorder#7]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/luzhi/dylr/util/logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "/home/ubuntu/luzhi/dylr/util/logger.py", line 65, in fatal_and_print
    if not app.win_mode:
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "main.pyw", line 3, in <module>
    import dylr.core.app as app
  File "/home/ubuntu/luzhi/dylr/core/app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "/home/ubuntu/luzhi/dylr/core/config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "/home/ubuntu/luzhi/dylr/core/record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "/home/ubuntu/luzhi/dylr/core/recording.py", line 8, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "/home/ubuntu/luzhi/dylr/core/danmu_recorder.py", line 7, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

**Comment by daqiang789** [comment]
root@instance-20220406-1847:/home/ubuntu/luzhi# python3 main.pyw
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/luzhi/dylr/util/logger.py", line 32, in log_uncaught_exceptions
    fatal_and_print(''.join(traceback.format_tb(tb)))
  File "/home/ubuntu/luzhi/dylr/util/logger.py", line 65, in fatal_and_print
    if not app.win_mode:
AttributeError: module 'dylr.core.app' has no attribute 'win_mode'

Original exception was:
Traceback (most recent call last):
  File "main.pyw", line 3, in <module>
    import dylr.core.app as app
  File "/home/ubuntu/luzhi/dylr/core/app.py", line 15, in <module>
    from dylr.core import version, config, record_manager, monitor
  File "/home/ubuntu/luzhi/dylr/core/config.py", line 11, in <module>
    from dylr.core import record_manager, app
  File "/home/ubuntu/luzhi/dylr/core/record_manager.py", line 7, in <module>
    from dylr.core.recording import Recording
  File "/home/ubuntu/luzhi/dylr/core/recording.py", line 8, in <module>
    from dylr.core.danmu_recorder import DanmuRecorder
  File "/home/ubuntu/luzhi/dylr/core/danmu_recorder.py", line 8, in <module>
    from google.protobuf import json_format
ModuleNotFoundError: No module named 'google'


还是不行呀，是不是需要升级啊

现在是Python 2.7.18

**Comment by LyzenX** [comment]
该项目不支持python2，请使用python3，建议使用3.8或3.9版本
另外，依赖都安装了没有：
``` bash
python3 -m pip install -r requirements.txt
```

**Comment by daqiang789** [comment]
================================================================================
Douyin Live Recorder v.20230418 by Lyzen
软件仅供科研数据挖掘与学习交流，因错误使用而造成的危害由使用者负责。
================================================================================
  File "main.pyw", line 25, in <module>
    main()
  File "main.pyw", line 9, in main
    run_cli()
  File "main.pyw", line 16, in run_cli
    app.init(False)
  File "/home/ubuntu/luzhi/dylr/core/app.py", line 51, in init
    record_manager.rooms = config.read_rooms()
  File "/home/ubuntu/luzhi/dylr/core/config.py", line 75, in read_rooms
    info = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

<class 'json.decoder.JSONDecodeError'>: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)


又出新问题了老哥，命运多舛呀

**Comment by LyzenX** [comment]
把room.json保存为无BOM格式
``` bash
vim room.json
:set nobomb
:wq!
```

**Comment by daqiang789** [comment]
完了又出新问题了


================================================================================
获取cookie中...
cookie获取完成
检测房间列表为空


然后就不动了

**Comment by LyzenX** [comment]
房间列表里有东西吗？看一下room.json

**Comment by daqiang789** [comment]
好了老哥，把room.json改成rooms.json就行了
